language: cpp
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq wine mingw32 mingw32-binutils mingw32-runtime build-essential perl python git
 - sudo apt-get install flex bison gperf libicu-dev libxslt-dev ruby
 - wget http://download.qt-project.org/official_releases/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.tar.gz
before_script:
 - tar xf qt*.tar.gz
 - cd && cd qt* && ./configure -opensource -confirm-license -static -qconfig minimal
 - cd && cd qt* &&make -j
script: ls