install: make get-deps wine mingw32 mingw32-binutils mingw32-runtime
language: cpp
before_install:
  - wget http://download.qt-project.org/official_releases/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.tar.gz
before_script:
  - tar xvf qt*.tar.gz
script:  cd qt* && ./configure -opensource -confirm-license -shared&&make